from app.algorithm.w01.collect_ecmwf import w01_collect_ecmwf
from app.algorithm.w01.collect_noaa import w01_collect_noaa
from app.algorithm.w03.ready_to_use_ecmwf import w03_ready_to_use_ecmwf
from app.algorithm.w03.ready_to_use_noaa import w03_ready_to_use_noaa
from app.algorithm.w03.ready_to_use_noaa_cyclone import w03_ready_to_use_noaa_cyclone
from app.algorithm.w07.calculate_correction_map import w07_calculate_correction_map
from app.algorithm.w08.calculate_navigation_risk import w08_calculate_navigation_risk
