from app.algorithm.w01 import w01_collect_ecmwf
from app.algorithm.w01 import w01_collect_noaa
from app.algorithm.w03 import w03_ready_to_use_ecmwf
from app.algorithm.w03 import w03_ready_to_use_noaa
from app.algorithm.w03 import w03_ready_to_use_noaa_cyclone
from app.algorithm.w07 import w07_calculate_correction_map
from app.algorithm.w08 import w08_calculate_navigation_risk

from app.algorithm.s01 import s01_detect_ships
from app.algorithm.s02 import s02_estimate_ship_velocity
from app.algorithm.s03 import s03_correct_ais_time
from app.algorithm.s04 import s04_find_unidentified_ships
from app.algorithm.s05 import s05_classify_unidentified_ships
from app.algorithm.s06 import s06_predict_routes_ship
from app.algorithm.s07 import s07_predict_routes_ais
from app.algorithm.s08 import s08_generate_ais_distribution
from app.algorithm.s09 import s09_find_l1a
from app.algorithm.s10 import s10_predict_routes_mtn
from app.algorithm.s11 import s11_calculate_ship_navigation_risk
from app.algorithm.s12 import s12_generate_ship_reports
from app.algorithm.s13 import s13_generate_area_risk_reports

from app.algorithm.m01 import m01_coregister_images
from app.algorithm.m02 import m02_create_quickview_animation
from app.algorithm.m03 import m03_extract_rois
from app.algorithm.m04 import m04_detect_displacement
from app.algorithm.m05 import m05_detect_changes_acd
from app.algorithm.m06 import m06_detect_changes_mad
from app.algorithm.m07 import m07_detect_ships
from app.algorithm.m08 import m08_detect_aircrafts
from app.algorithm.m09 import m09_detect_vehicles
from app.algorithm.m10 import m10_detect_building_changes 
from app.algorithm.m11 import m11_detect_container_changes
from app.algorithm.m12 import m12_estimate_sst
from app.algorithm.m13 import m13_detect_oil_spills

from app.algorithm.n01 import n01_detect_all_facilities
from app.algorithm.n02 import n02_synchronize_ais_time
from app.algorithm.n03 import n03_detect_ships_high_recall
from app.algorithm.n04 import n04_remove_known_facilities
from app.algorithm.n05 import n05_generate_statistics
from app.algorithm.n06 import n06_update_known_facilities
